<tr class="<%evenodd%>" <%style%>>
  <!--<td><input type="checkbox" id="cb-<%numLine%>"/></td>-->
   <td class="right"><%numLine%></td>
  <td><a href="<%page.fulluri%>?minDateTimeSecFilter=<%ut3x.logs.minDateTimeSecFilter%>&maxDateTimeSecFilter=<%ut3x.logs.maxDateTimeSecFilter%>"><%ut3x.logs.ts%></a></td>
  <td><a href="<%page.fulluri%>?logTypeFilter=<%ut3x.logs.logtype%>"><%ut3x.logs.logtype%></a></td>
  <td><a href="<%page.fulluri%>?srcPNFilter=<%ut3x.logs.srcPN%>"><%ut3x.logs.srcPN%></a></td>
  <td><a href="<%page.fulluri%>?srcPNFilter=<%ut3x.logs.destPN%>"><%ut3x.logs.destPN%></a></td>
  <td><%ut3x.logs.data%></td>
</tr>
